### ISSUE TITLE
throw TypeError: 'TMPDIR' while running

### ISSUE THREAD

**Issue by qzhai** [Nanne/pytorch-NetVlad#1]
![image](https://user-images.githubusercontent.com/10611603/51291005-987bf380-1a40-11e9-8be7-88e6694b5be6.png)

**Comment by Nanne** [comment]
the TMPDIR is a ENV variable that gets set on the cluster I've been running things on, if you get a keyerror you can just remove/replace the default value and specify a path using the --cachePath flag.

**Comment by qzhai** [comment]
Hi Nanne,
Did you evaluate the model trained using '--arch=alexnet'? I found the recalls Relja mentioned in paper is trained from the pretrained alexnet model, but I found the default flag --arch is vgg16 in your code, if you have no time to do the test, I will do that.

**Comment by Nanne** [comment]
After 7 epochs the score for alexnet levels off a bit, and you get around:
====> Recall@1: 0.6857
====> Recall@5: 0.8462
====> Recall@10: 0.8927
====> Recall@20: 0.9356

You can probably train it further and get slightly higher, but it definitely performs worse than the vgg16 model.
