### ISSUE TITLE
Some questions about calculating cluster

### ISSUE THREAD

**Issue by skJack** [Nanne/pytorch-NetVlad#10]
First ,thanks for the remarkable work.
My question is when i want to train this model , i should train cluster and save it firstly. But i check your code and find when you train cluster, you use the model which not trained before, that means the model is random. I think the descriptors trained by this network is not reliable.

**Comment by Nanne** [comment]
Unless you call the model with the --fromscratch flag the model that is loaded is a model that is pretrained on the ImageNet dataset, as was described in the original paper. So its not random, and the descriptors are fairly reliable, of course they improve from finetuning, but its not a concern for training.
