### ISSUE TITLE
What is the function of the h5feat?

### ISSUE THREAD

**Issue by ShilangChen1011** [Nanne/pytorch-NetVlad#17]
What is the function about the followed code?
```
train_set.cache = join(opt.cachePath, train_set.whichSet + '_feat_cache.hdf5')
        with h5py.File(train_set.cache, mode='w') as h5: 
            pool_size = encoder_dim
            if opt.pooling.lower() == 'netvlad': pool_size *= opt.num_clusters
            h5feat = h5.create_dataset("features", 
                    [len(whole_train_set), pool_size], 
                    dtype=np.float32)
            with torch.no_grad():
                for iteration, (input, indices) in enumerate(whole_training_data_loader, 1):
                    input = input.to(device)
                    image_encoding = model.encoder(input)
                    vlad_encoding = model.pool(image_encoding) 
                    h5feat[indices.detach().numpy(), :] = vlad_encoding.detach().cpu().numpy()
                    del input, image_encoding, vlad_encoding
```

The h5feat was defined by the aboved code, but it is not used by the behind code.
Why is it defined?

**Comment by Nanne** [comment]
h5feat is a HDF5 file used to cache extracted features, it is subsequently used when creating the training triplets here: https://github.com/Nanne/pytorch-NetVlad/blob/master/pittsburgh.py#L220

The 'correct' positive is selected from the potential positives based on visual similarity, and similarly the hard negatives are selected based on whether they fall within the margin.

So it is defined such that you don't have to pass every possible image through the network whenever trying to create triplets. This caching is done once per epoch, just as in the original netvlad code/paper.
