### ISSUE TITLE
Where can I download the Pittsburgh 250k dataset

### ISSUE THREAD

**Issue by fanhuanhuan** [Nanne/pytorch-NetVlad#20]
Where can I download the Pittsburgh 250k dataset，can you give me the url, thank you!

**Comment by jinyeying** [comment]
no Pittsburgh 250k dataset, can you share with me? thanks

**Comment by Nanne** [comment]
See https://www.di.ens.fr/willow/research/netvlad/ for instructions on how to obtain the datasets.
