### ISSUE TITLE
About Tokyo dataset

### ISSUE THREAD

**Issue by gmberton** [Nanne/pytorch-NetVlad#21]
Unlike for pitts30k, in the Tokyo dataset the query images are included in the gallery (in train and val set). To solve this issue, in the original matlab implementation the authors add a constraint to choose the positives for each query, which is that the positive should have a different date with respect to the query.
function posIDs= nontrivialPosDb(db, iDb)
        [posIDs, dSq]= db.cp.getPosDbIDs(iDb);
        posIDs= posIDs(dSq>1 & dSq<=db.nonTrivPosDistSqThr & db.dbTimeStamp(iDb)~=db.dbTimeStamp(posIDs) );
    end

To solve this it is necessary to filter the nontrivial_positives in QueryDatasetFromStruct.__init__, in a way that the positives with the same date as the query are filtered away, and also in the evaluation part, it is needed to filter away the predictions with the same date of the query.
Hope this helps with the Tokyo issues

**Comment by Nanne** [comment]
Thanks for the pointers, I did something similar in the past, but never found much reason to use the Tokyo dataset..
