### ISSUE TITLE
Pretrained recalls

### ISSUE THREAD

**Issue by gmberton** [Nanne/pytorch-NetVlad#23]
I ran some tests (without performing any training) just by using the pretrained nets + max pool, and the recalls are always 5 to 10 points lower compared to off-the-shelf results on the netvlad paper. Do you think it is only because of the pretrained net, or do you know of any other difference with the original matlab code from the authors?

**Comment by Nanne** [comment]
It's a tricky issue to debug, but when I loaded the weights from the matlab model it usually worked a bit better. Its just that there was no reliable way to load those weights, so it made the code error prone and unstable, which made me opt for using a pytorch native model.

I haven't been able to find any other difference with the original, but if you find any I'd be happy to look into it.

**Comment by gmberton** [comment]
Thank you for the quick response. I've been stuck with this issue for some time already, so a few days ago I installed matlab to investigate further. All I managed to do was to extract the features with the matlab code, save them on a file, read them with python and calculate the recalls with your code. The recalls that I obtained with your code were identical to those obtained in matlab. 
Therefore the difference should be within the features extraction process. I guess there couldn't be any difference between matlab and torch L2 layer or max pool right? By any chance, do you remember how big was the improvement when using the weights from matlab model, was it close to 5%?

**Comment by Nanne** [comment]
I got it to work by just loading the weights from matlab, so those layers shouldnt be the issue.

It was a while back, so I don't remember how much of a difference it made.
