### ISSUE TITLE
What does vladv2 indicate?

### ISSUE THREAD

**Issue by LimHyungTae** [Nanne/pytorch-NetVlad#24]
I really appreciate your effort in advance :)

For the first time, when I was a newbie of NetVlad, I set vladv2 as True, but it does not show better performance than the case whose vladv2 is False.

So, I'm wondering what does the vladv2 flag indicate (I believe it is likely to be related to normalization or something)

I'm looking forward to hearing from you.

**Comment by Nanne** [comment]
https://github.com/Nanne/pytorch-NetVlad/issues/18#issuecomment-584146656 :)
