### ISSUE TITLE
Questions about alpha in netvlad.py

### ISSUE THREAD

**Issue by key-rnaker** [Nanne/pytorch-NetVlad#25]
hi!
i have a question about alpha in netvlad.py
in the paper, they define the alpha like below.
α is computed so that the the ratio of the largest and the second largest soft assignment weight a_k(x_i) is on average equal to 100.

1) what does it mean?
2) in your netvlad.py, you compute alpha like this
```
knn = NearestNeighbors(n_jobs=-1) #TODO faiss?
knn.fit(traindescs)
del traindescs
dsSq = np.square(knn.kneighbors(clsts, 2)[1])
del knn
self.alpha = (-np.log(0.01) / np.mean(dsSq[:,1] - dsSq[:,0])).item()
```

but as i know, the function ```knn.kneighbors``` returns [  neighbor distance array , neighbor index array]
so is ```dsSq``` a neighbor index array of returns?
i think ```dsSq``` should be changed to distance not the index

**Comment by Nanne** [comment]
Note that the code you copied is for the v2 layer, while v1 is the one that gets used. As for whether its correct or not, I followed the implementation of the original paper (and not necessarily what they said in the paper): https://github.com/Relja/netvlad/blob/master/addLayers.m#L58

If you see any differences between the two implementations you're welcome to submit a PR, but in this case it seems to me they are the same.
