### ISSUE TITLE
what does utmDb, utmQ, posDistThr, posDistSqThr and nonTrivPosDistSqThr mean

### ISSUE THREAD

**Issue by yaqianchen** [Nanne/pytorch-NetVlad#26]
Hi, I am an undergraduate student who has just started to learn Machine learning. I really want to reproduce the project on my custom dataset. 
First, thank you so much for your remarkable work.
However, I am confused about what does utmDb, utmQ, posDistThr, posDistSqThr and nonTrivPosDistSqThr stand for in tokyo247.py. I guess numDb and numQ are the number of database images and query images, it is right?

**Comment by Nanne** [comment]
Correct, num is short for number, and Q stands for queries. Db for database.

utm is the [Universal Transverse Mercator coordinate](https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system) system, i.e., it tells you where in Tokyo the images are taken.

PosDisThr is the positive distance threshold, Sq is the squared version on that, and nonTrivPosDisSqThr is the non trivial positive distance threshold. These thresholds are in meters and are the various distances used to determine which images are positives or potential positives. 

Note that I didn't come up with these, this is all based on the datasets specifications from the original netvlad authors: https://www.di.ens.fr/willow/research/netvlad/
