### ISSUE TITLE
Question about 'self.cache = None'

### ISSUE THREAD

**Issue by RaymondLmx** [Nanne/pytorch-NetVlad#27]
In line 208 of pittsburgh.py:
        self.cache = None

makes me confused that in line 214 the h5 file can not be loaded with no path here. Does it mean we don't need to load h5 file here or just you don't set it

**Comment by Nanne** [comment]
That line is just there to define the variable, but to indicate that the filepath itself is unknown. The actual file location is given during training: https://github.com/Nanne/pytorch-NetVlad/blob/master/main.py#L88

The logic to create the cache is kept outside of that file, and perhaps it would've been better to have it inside there, but nonetheless the cache is needed if you want to iterate through the dataset.

**Comment by RaymondLmx** [comment]
Thank you so much that I realize this logic today.
