### ISSUE TITLE
confused with ground truth

### ISSUE THREAD

**Issue by qzhai** [Nanne/pytorch-NetVlad#3]
I read the code, thank you for the excellent work. I have a confused understanding about the ground truth, and I will show the situation with a example.
I found the Database can be classifid into smaller groups, each group has 24 images share the same Lantitute and Lontitute, then when ground truth is searched using Lantitute and Lontitute, each query gets the same distance to all the images in the same db group, that is we can get top-24 ground truth with the same distance, the situation is simplified as bellow,
utmDb (3,2) (3,2) (3,2) (3,2) ... (3,2) / (5,4) (5,4) ... (5,4)
utmQ   (1,1) ...
then, the ground truth index for utmQ[0] is [0, 1, 2, 3, ..., 23], during the NetVLAD test, VLAD vector is used to estimate the similarity, if a query belongs to place 1 and get the best top-10 matched index [23  22 21 20 19, 18, 17, 16, 15, 14], then the top-10 recognition percentage will be zero, as the top-10 ground truth is [0, 1, 2, ..., 9] but the top-10 VLAD matched result is [23, 22, ..., 14].
It seems unresonable, how to handle this situation and get a better evaluation way?

**Comment by Nanne** [comment]
Each image, in both the database and the query set is obtained by dividing a panorama image taken at a single location into 24 images. As such, these 24 images all share the same location as the original panorama. The ground truth for a specific query is thus a database image that was nearby, but is typically not the exact same location (but within a few meters). This is the setup as described in the paper, and the dataset a prepared by the authors.

I understand what your example is trying to show, and obviously a positive match may be found outside of the 25 meter threshold as set in the paper. And this could be one way to test this, you can calculate the performance at different distance thresholds, as in: http://openaccess.thecvf.com/content_ICCV_2017/papers/Vo_Revisiting_IM2GPS_in_ICCV_2017_paper.pdf

However, given that the matching is done based on visual similarity it seems unlikely that all images that belong to a single panorama will be matched, as many of the different view directions in the panorama won't match the query image. 

If your goal is to do instance retrieval then the NetVlad setup seems preferred, but if you're simply trying to approximately localise then different distance thresholds might be preferred.

**Comment by qzhai** [comment]
That makes sense, I think I have a more clearly understanding for evaluation part, I'll read the ICCV paper, thank you Nanne.
