### ISSUE TITLE
Question about the checkpoint given

### ISSUE THREAD

**Issue by RaymondLmx** [Nanne/pytorch-NetVlad#37]
When I load the checkpoint given by you, it will show this error message:
```
Missing key(s) in state_dict: "pool.conv.bias".
```
Does it mean you use vlad instead of vladv2 here? And please tell me how can I deal with it that I can train my model based on this checkpoint.

**Comment by Nanne** [comment]
The provided checkpoint is trained with default settings, which uses vlad and not vladv2.

Again, if there is an issue with the code please report it here, if its an issue with how to use it then I cannot help you.
