### ISSUE TITLE
What dose nonTrivPosDistSqThr mean in pittsburgh.py?

### ISSUE THREAD

**Issue by zhanqan** [Nanne/pytorch-NetVlad#4]
What dose nonTrivPosDistSqThr mean in pittsburgh.py? I find it in the .mat file, but i don't understand its meaning. For example, in pitts30k_test.mat, nonTrivPosDistSqThr=100.

**Comment by Nanne** [comment]
This is a naming convention used by the original authors. It's the Squared threshold for the non trivial positive distance. During training the positives in the triplets are sampled from the set of images within this threshold, in this case 100 units, or 10 meters.
