### ISSUE TITLE
Where is the cache path in pittsburgh？

### ISSUE THREAD

**Issue by QinZiwen** [Nanne/pytorch-NetVlad#40]
Line 214 in Pittsburgh.py
```
self.cache = None
```
but，line 220 will read it：
```
with h5py.File(self.cache, model='r') as h5:
```

so, where is the cache path?

thanks

**Comment by Nanne** [comment]
It's set outside the class (not the most elegant solution): https://github.com/Nanne/pytorch-NetVlad/blob/master/main.py#L88

**Comment by QinZiwen** [comment]
Thank you for your reply
