### ISSUE TITLE
Sorry for another question!

### ISSUE THREAD

**Issue by Fleurrr** [Nanne/pytorch-NetVlad#45]
The Pittsburgh datasets I got contains ``000`` to ``010`` directories ,but only contains ``000`` to ``008`` 9 subdirectories in ``queries_real``.
And I think that's the reason cause the error .
Is it possible not to use ``009`` ``010`` two folder data?
Could you please give me some hints for the error?

**Comment by Nanne** [comment]
Structure of the dataset is supposed to match that of the .mat files loaded here: https://github.com/Nanne/pytorch-NetVlad/blob/master/pittsburgh.py#L29-L67

As such you can either adjust the dataset file structure to match that, or conversely you can edit the structure of the .mat files.
