### ISSUE TITLE
Error with faiss kmeans argument

### ISSUE THREAD

**Issue by mrgransky** [Nanne/pytorch-NetVlad#48]
Running:
`$ python main.py --mode=cluster --arch=vgg16 --pooling=netvlad --num_clusters=64`
return error:
```
Traceback (most recent call last):
  File "main.py", line 478, in <module>
    get_clusters(whole_train_set)
  File "main.py", line 251, in get_clusters
    kmeans = faiss.Kmeans(encoder_dim, opt.num_clusters, niter, verbose=False) # ERROR!!!!!!!!!!!
TypeError: __init__() takes 3 positional arguments but 4 were given
```
in `main.py` and `def get_clusters(cluster_set)` one can replace 
`kmeans = faiss.Kmeans(encoder_dim, opt.num_clusters, niter, verbose=False)` 
with 
`kmeans = faiss.Kmeans(encoder_dim, opt.num_clusters, niter=niter, verbose=False)` 
to get rid of that error!

**Comment by Nanne** [comment]
This is the same issue as spotted in #44 and fixed with the latest commit, is it not? Or do you get this error with the latest commit?

**Comment by mrgransky** [comment]
you are right!  :+1: 
my commit was little old
