### ISSUE TITLE
How to replace utm coordinates with GPS coordinates in my dataset?

### ISSUE THREAD

**Issue by zhanqan** [Nanne/pytorch-NetVlad#5]
Can I use GPS coordinates in my dataset to replace the utm coordinates to generate .mat files ? Do I need to modify the code which is used to find radius_neighbors?

**Comment by Nanne** [comment]
I would assume its easier to just convert the GPS coordinates to utm coordinates. I have no experience with this though as I've simply used the data as indicated on https://www.di.ens.fr/willow/research/netvlad/

A quick google search returned this: https://pypi.org/project/utm/, perhaps it might do what you need.

If you do want to use GPS you would indeed have to adjust the radius_neighbors to use a different radius, and a suitable distance measure.
