### ISSUE TITLE
Question about the training dataset

### ISSUE THREAD

**Issue by hyeongilee** [Nanne/pytorch-NetVlad#59]
Hi, Thanks for providing the code.
It seems that the distance between features was used to obtain positive and negative data.(in __getitem__ of QueryDatasetFromStruct)
Shouldn't the utm(gps) distance be used to obtain positive and negative datasets when training?

**Comment by Nanne** [comment]
Potential positives and negatives are initially selected based on utm distance: https://github.com/Nanne/pytorch-NetVlad/blob/master/pittsburgh.py#L198-L206

From these potentials the final selections are made according to feature distance, this is in accordance with the Netvlad approach described in the paper.
