### ISSUE TITLE
TypeError: Indexing arrays must have integer dtypes occured when training

### ISSUE THREAD

**Issue by 2u4dk123** [Nanne/pytorch-NetVlad#61]
Hello everyone! I'm new in computer vision and I'm studying CSIE in NUU (National United University) now.
I want to get familiar with this program so I tried to redo the training and test it on my computer.
I'm useing virtual env in anaconda3 and here is what I use.
GPU : RTX 2060 with 497.09 version of driver
CUDA : 10.2
pytorch : 1.10.0
Altough it took me some time to solve env problem but it finally succeed.
But next question occured and I cant find out anything wrong.

The bug report is below

(NetVLAD_python3_7) C:\Users\CSIE404>cd pytorch-NetVlad-master

(NetVLAD_python3_7) C:\Users\CSIE404\pytorch-NetVlad-master>python main.py --mode=train --arch=vgg16 --pooling=netvlad --num_clusters=64
Namespace(arch='vgg16', batchSize=2, cacheBatchSize=12, cachePath='TMPDIR', cacheRefreshRate=1000, ckpt='latest', dataPath='D:/Work/pytorch-NetVlad-master/nfs/ibrahimi/data/', dataset='pittsburgh', evalEvery=1, fromscratch=False, lr=0.0001, lrGamma=0.5, lrStep=5, margin=0.1, mode='train', momentum=0.9, nEpochs=30, nGPU=0, nocuda=False, num_clusters=64, optim='SGD', patience=10, pooling='netvlad', resume='', runsPath='D:/Work/pytorch-NetVlad-master/nfs/ibrahimi/runs/', savePath='checkpoints', seed=123, split='val', start_epoch=0, threads=8, vladv2=False, weightDecay=0.001)
===> Loading dataset(s)
====> Training query set: 7320
===> Evaluating on val set, query count: 7608
===> Building model
===> Training model
===> Saving state to: D:/Work/pytorch-NetVlad-master/nfs/ibrahimi/runs/Dec09_04-48-50_vgg16_netvlad
C:\Users\CSIE404\anaconda3\envs\NetVLAD_python3_7\lib\site-packages\torch\optim\lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
C:\Users\CSIE404\anaconda3\envs\NetVLAD_python3_7\lib\site-packages\torch\optim\lr_scheduler.py:154: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)
====> Building Cache
Allocated: 60039168
C:\Users\CSIE404\anaconda3\envs\NetVLAD_python3_7\lib\site-packages\torch\cuda\memory.py:386: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  FutureWarning)
Cached: 3183476736
Traceback (most recent call last):
  File "main.py", line 512, in <module>
    train(epoch)
  File "main.py", line 114, in train
    negCounts, indices) in enumerate(training_data_loader, startIter):
  File "C:\Users\CSIE404\anaconda3\envs\NetVLAD_python3_7\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\CSIE404\anaconda3\envs\NetVLAD_python3_7\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "C:\Users\CSIE404\anaconda3\envs\NetVLAD_python3_7\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "C:\Users\CSIE404\anaconda3\envs\NetVLAD_python3_7\lib\site-packages\torch\_utils.py", line 434, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\CSIE404\anaconda3\envs\NetVLAD_python3_7\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\CSIE404\anaconda3\envs\NetVLAD_python3_7\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\CSIE404\anaconda3\envs\NetVLAD_python3_7\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\CSIE404\anaconda3\envs\NetVLAD_python3_7\lib\site-packages\torch\utils\data\dataset.py", line 363, in __getitem__
    return self.dataset[self.indices[idx]]
  File "C:\Users\CSIE404\pytorch-NetVlad-master\pittsburgh.py", line 230, in __getitem__
    negFeat = h5feat[negSample.tolist()]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\CSIE404\anaconda3\envs\NetVLAD_python3_7\lib\site-packages\h5py\_hl\dataset.py", line 783, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "C:\Users\CSIE404\anaconda3\envs\NetVLAD_python3_7\lib\site-packages\h5py\_hl\selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py\_selector.pyx", line 272, in h5py._selector.Selector.make_selection
  File "h5py\_selector.pyx", line 183, in h5py._selector.Selector.apply_args
TypeError: Indexing arrays must have integer dtypes

Everything is ok when I do cluster and test, it only show up when training.
I dont know what information else I can provide but if you need more just tell me. I will reply right away.
I'm not a very good student but I did serach for some keywords like _dataloader TypeError_ , _TypeError: Indexing arrays must have integer dtypes_ , _h5py TypeError_ . 
But there is just no solution for me.
I tried to read code but I cant get it like it keeps show some file else. Should I check _main.py_ or _dataloader.py_ or __utils.py_ and I cant even find _h5py\_selector.pyx_ .
I was stocked in this bug for days and not even get progress.
I hope there is someone can recognize this problem and Please if you can show me how to fix it. I'm run out of my juice, please.

[https://github.com/Nanne/pytorch-NetVlad/blob/master/main.py](url)

**Comment by yuanyuanjerry** [comment]
Have you ever tried: pip install h5py==2.10.0

**Comment by Nanne** [comment]
This seems indeed to be related to h5py, you could try another version as suggested. Alternatively, you could try explicitly casting the `negSample` to ints, along the lines of: `negFeat = h5feat[negSample.astype(int).tolist()]`

**Comment by 2u4dk123** [comment]
Thank you both. I'll try right now.
I dont know what to say but really thank you.

**Comment by 2u4dk123** [comment]
@Nanne Sir it works!! Thank you very much!!
Now I'm trying to train the model on my pc.
Really thank you !!
@yuanyuanjerry Also thank you for help me with this bug, thanks alot.

**Comment by XinLan12138** [comment]
> This seems indeed to be related to h5py, you could try another version as suggested. Alternatively, you could try explicitly casting the `negSample` to ints, along the lines of: `negFeat = h5feat[negSample.astype(int).tolist()]`

I also encountered the same problem with @2u4dk123 , but I don't really understand the alternative approach. Can you explain where should I put this lines?

**Comment by yuanyuanjerry** [comment]
In pittsburgh.py, line 230.

**Comment by XinLan12138** [comment]
Oh thx! I figured it out. BTW, do you have this warning information
condisering n_jobs=1? I changed all n_jobs for knn to be 1 but this warning
still show up.


yuanyuanjerry ***@***.***>于2021年12月31日 周五09:17写道：

**Comment by yuanyuanjerry** [comment]
I just set n_jobs=1 and the problem is solved.
But I don’t think this is a good solution, and I didn't find any other way to solve this problem.

**Comment by LyyyyyyyN** [comment]
> I just set n_jobs=1 and the problem is solved. But I don’t think this is a good solution, and I didn't find any other way to solve this problem.

Hello, do you find another solution rather than set n_jobs = 1? I also met this problem. Although the training could be completed, I found the result was not good.

**Comment by yuanyuanjerry** [comment]
No, and I think n_jobs shouldn't affect performance.
