### ISSUE TITLE
Input type and weight type are not the same

### ISSUE THREAD

**Issue by TuShuqi** [Nanne/pytorch-NetVlad#62]
hello, I want to ask you for help. When I run your code to test after trained, there is always a error: 
Traceback (most recent call last):
  File "main.py", line 488, in <module>
    recalls = test(whole_test_set, epoch, write_tboard=False)
  File "main.py", line 187, in test
    image_encoding = model.encoder(input)
  File "/opt/conda/envs/vprt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/vprt/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/conda/envs/vprt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/vprt/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/opt/conda/envs/vprt/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

If you can help me, I will be very grateful for you.

**Comment by Nanne** [comment]
Somehow the data that you are loading is on the GPU, but the model (and thus its weights) are on CPU. 

Any chance that you're seeing this print statement when loading the model https://github.com/Nanne/pytorch-NetVlad/blob/master/main.py#L482 ?

Does it work if you try running it with `--nocuda` ?

**Comment by TuShuqi** [comment]
Thank you very much for your reply!



When I searched for solutions online, I got the same statement as you. But even through I did not find a solution.


I did see this print statement when loading the model. 



I will try to running it with --nocuda later to see the effect.


Do you have any suggestions for me ?

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nanne/pytorch-NetVlad"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月3日(星期一) 晚上7:49
***@***.***&gt;;
抄送:&nbsp;"Tu ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nanne/pytorch-NetVlad] Input type and weight type are not the same (Issue #62)





 
Somehow the data that you are loading is on the GPU, but the model (and thus its weights) are on CPU.
 
Any chance that you're seeing this print statement when loading the model https://github.com/Nanne/pytorch-NetVlad/blob/master/main.py#L482 ?
 
Does it work if you try running it with --nocuda ?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Nanne** [comment]
If you see that print statement in the output it means that the path to the checkpoint provided for resuming is wrong, or at least that no checkpoint could be found at that location. 

As long as you get "no checkpoint found at" you can't do a valid test anyway.

**Comment by TuShuqi** [comment]
So that's it! your narration made me know the reason for the error.


Thank you very much!


In order not to disturb you excessively, I will look for a solution on the Internet next.


Thank you again for replying to me and it helps me a lot.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nanne/pytorch-NetVlad"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月3日(星期一) 晚上8:01
***@***.***&gt;;
抄送:&nbsp;"Tu ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nanne/pytorch-NetVlad] Input type and weight type are not the same (Issue #62)





 
If you see that print statement in the output it means that the path to the checkpoint provided for resuming is wrong, or at least that no checkpoint could be found at that location.
 
As long as you get "no checkpoint found at" you can't do a valid test anyway.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
