### ISSUE TITLE
\pytorch-NetVlad-master\pittsburgh.py", line 188, in collate_fn     query, positive, negatives, indices = zip(*batch) ValueError: not enough values to unpack (expected 4, got 2)

### ISSUE THREAD

**Issue by pareespathak** [Nanne/pytorch-NetVlad#64]
Is this problem of collating function? I am training this on the Pittsburgh dataset.

**Comment by Nanne** [comment]
You haven't provided enough information, it also could be that the changes you made to the code led to this. In general I'm happy to help with this codebase, but I cannot help debug problems resulting from modification. Best of luck!
