### ISSUE TITLE
Question about the positives and negatives

### ISSUE THREAD

**Issue by salt0107fish** [Nanne/pytorch-NetVlad#66]
Hi! Thanks for your code.
I'm not sure if I understand correctly, but it seems that the positive and negative samples using threshold based on the utm are too many, especially the negative.  Almost all samples were included. Is that right?
Have you ever tried to change the threshold to reduce the number of negatives? Or is the current threshold the best result in your experiment?
Thank you!

**Comment by Nanne** [comment]
Hi, the those values are the values used in the paper: https://arxiv.org/abs/1511.07247

Based on these values you should really only get a small number of the samples, if you're getting almost all samples then something is going wrong.

**Comment by salt0107fish** [comment]
Thank you for your reply. I'll check it~
