### ISSUE TITLE
tokyo24/7 dataset training

### ISSUE THREAD

**Issue by TuShuqi** [Nanne/pytorch-NetVlad#68]
Thanks a lot for your work about pytorch code.
When I tried to use the tokyo24/7 dataset, I found that the code could not run smoothly. I tried to look for the problem and found that the margin may be too small. When I changed margin=2, the code ran smoothly, but I also encountered some problems, that is, all epoch recall rates were all equal to 1. This is obviously wrong and would like to ask you for help explaining this.

![image](https://user-images.githubusercontent.com/72071329/163131010-5ad4804f-4d1d-45c9-b9c2-5f2d7f6c7c57.png)

====> Building faiss index
====> Calculating recall @ N
====> Recall@1: 1.0000
====> Recall@5: 1.0000
====> Recall@10: 1.0000
====> Recall@20: 1.0000

**Comment by Nanne** [comment]
As discussed in https://github.com/Nanne/pytorch-NetVlad/issues/8 it should work with the default code, but the performance will be lower than the paper. Are you loading the data correctly?

**Comment by TuShuqi** [comment]
Thank you for your reply!
I think I should have loaded the dataset correctly. If the dataset is not loaded correctly, the code may report an error because the path to the image cannot be found. But my current situation is just that the recall rate is not normal, I haven't found where the problem is.

**Comment by Nanne** [comment]
I'm not sure if you can definitively say that the dataset is loaded correctly based on that; you're getting perfect performance so an artifact in the data would be my first guess. But unfortunately I cannot reproduce this error, and I do not have enough information to help you debug it..

**Comment by TuShuqi** [comment]
I have verified that the md5sum value of the downloaded dataset is correct. Then I just re-decompressed the dataset for training, and the result is still the same as before.

If you want to talk about the problem of the dataset, it may be because I modified the path of the dataset (tokyo247.py) as shown below:
![image](https://user-images.githubusercontent.com/72071329/163164227-a5c10dfc-6f2b-4f70-8ceb-737aab2a7b50.png)

But in fact, I was looking for convenience, so after decompressing the TokyoTimeMachine dataset, I put all the ".mat" files in the "./TokyoTimeMachine/images/" folder. I think this should be no problem.

Where do you think the problem should be? I will refer to your suggestion to debug again to find the problem.

**Comment by TuShuqi** [comment]
I have found a solution, thank you very much for your tips!

**Comment by Nanne** [comment]
Great to hear; would you mind sharing what the problem was and how you solved it? Might be useful for others as well!

**Comment by TuShuqi** [comment]
Yeah, just like the question raised by another friend, just follow his solution.

![image](https://user-images.githubusercontent.com/72071329/163504533-95748a45-8f4d-4641-8d49-23e8da110f78.png)

He studied the MATLAB code very seriously, and found the logic in the pytorch code is different, I just refer to his solution to modify tokyo.py accordingly.

**Comment by xX-Conan-Xx** [comment]
> Yeah, just like the question raised by another friend, just follow his solution.
> 
> ![image](https://user-images.githubusercontent.com/72071329/163504533-95748a45-8f4d-4641-8d49-23e8da110f78.png)
> 
> He studied the MATLAB code very seriously, and found the logic in the pytorch code is different, I just refer to his solution to modify tokyo.py accordingly.

Hi @TuShuqi Do you mind sharing your tokyo.py file? I encountered the same problem.
Thank you very much.

**Comment by whu-lyh** [comment]
I meet the same problem, Need the help, thanks @TuShuqi
