### ISSUE TITLE
Can't  get Pittsburgh 250k  dataset, link failed

### ISSUE THREAD

**Issue by Nothingzl** [Nanne/pytorch-NetVlad#69]
Can't  get Pittsburgh 250k  dataset, link failed,
Running this code requires a copy of the Pittsburgh 250k (available [here](http://www.ok.ctrl.titech.ac.jp/~torii/project/repttile/))

**Comment by Nanne** [comment]
Please see: https://github.com/Relja/netvlad/issues/42 Thanks!

**Comment by liuqinglong110** [comment]
I found the download link [https://data.ciirc.cvut.cz/public/projects/2015netVLAD/Pittsburgh250k/](https://github.com/Nanne/pytorch-NetVlad/issues/url)
I was discovered by a issue related links: [https://github.com/Nanne/pytorch-NetVlad/issues/19](https://github.com/Nanne/pytorch-NetVlad/issues/url)
suggested that read.
