### ISSUE TITLE
How to implement this code to another dataset?

### ISSUE THREAD

**Issue by jspark1213** [Nanne/pytorch-NetVlad#73]
Hi.
First, thanks to your work!
I want to implement this code to the another dataset which is not for the place recognition(original task of netVLAD paper).
The task I try to implement is camera pose estimation. Indeed my dataset has GT, thus I can calculate the recall or any other evaluation metrics on my way.
I don't know about matlab well, so I can not implement the official code of netVLAD.
Anyway, the first question is about the appropriate structure of dataset.
I can't read the .mat file, so I don't know how to adjust the stucture of my dataset.
The second question is "How can I adjust the size of DB (the retrieved images are from here, right?) ?"
I want to make result with half size of gallery(DB).
I think it is possible if I can handle the struct file.
As I think, this question is quite silly, but please help me :)...

**Comment by Nanne** [comment]
This function reads .mat files with python: https://github.com/Nanne/pytorch-NetVlad/blob/master/pittsburgh.py#L73-L99

If you make an appropriate .mat file for your dataset you should be able to load a different dataset (you can compare the tokyo247 and the pittsburgh files). Alternatively, you can change how the metadata is loaded if you dont want to use .mat - just check the function out above to see what is needed.

Netvlad is mostly for retrieval though, isn't camera pose estimation usually done as classification? Might not be the best path to go down.

**Comment by jspark1213** [comment]
Thanks to answer.
I'll check it.
Image retrieval method is the one way to estimate camera pose well. Not only the classification, but also the image retrieval  is used for the estimation. For reconstructing 3D map which can be used for pose estimaion, the image pairs are necessary. The feature vector from netVLAD is used to make those image pairs, in this case these feature vectors are called "global feature".

**Comment by jspark1213** [comment]
Hi again! Is there a way to apply PCA on netVLAD using this repository? The default number of dimension(n_cluster * enc_dim) is too big to calculate retrieval. I want to reduce the output dimension of netVLAD layer as 2048 or 1024. I won't reopen this issue btw. @Nanne

**Comment by Nanne** [comment]
I decided not to add PCA to this repo because there is nothing specific happening. The way to apply PCA is to extract the embeddings for the train set, learn the PCA matrix on that and then use it during test/inference to map the high dimensional embeddings to a lower dimension.
