### ISSUE TITLE
How to fix "TMPDIR" error?

### ISSUE THREAD

**Issue by Doublewater-jpg** [Nanne/pytorch-NetVlad#75]
Hi, I have some problem while I am trying to execute the program. I create a conda environment with python3.8 and install all packages (pytorch, scipy, ....) in it. Then change to the directory that python files in. Then execute the command:

`python main.py --mode=train --arch=vgg16 --pooling=netvlad --num_clusters=64`

Then it comes out the messages:

Traceback (most recent call last):
  File "main.py", line 51, in <module>
    parser.add_argument('--cachePath', type=str, default=environ['TMPDIR'], help='Path to save cache to.')
  File "C:\Users\york1\Anaconda3\envs\python37\lib\os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'TMPDIR'

I didn't find solution or similar way to solve this, I thought it was unsupported by some version of python.
I tried on python3.8 to python3.7 with those package required. But it still output the same error.
Then attempt on python3.6, but it seems to unavailable to install pytorch (I tried v1.12~v1.0).

I don't have that much practical experience in pytorch and construct a deep learning model, so it will be great if the explanation is as detailed as possible and also provided the guide step by step. Also if I want to train with other datasets, what are the restrictions on the input? 

Sorry for my bad English, hope that I interpret my questions clear, thanks for all of you willing to answer my questions!!!

**Comment by Nanne** [comment]
The --cachePath is the location where the cache will be saved, this default to `environ['TMPDIR']`, which is an environment variable that should point to where your tmp dir is (`/tmp/` on most linux systems I believe). If it can't find that value you can either set the [environment variable ](https://en.wikipedia.org/wiki/Environment_variable)manually, or you can just change the argument to use some other location.
