### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Anuradha-Uggi** [Nanne/pytorch-NetVlad#77]
Hi,
I was trying to train the model with training batch size = 1 and negSample=4. Parameters k=1024, number of channels 256 each with spatial dimension 64 by 64. Memory explodes when the feature map is fed to the NetVLAD pooling layer, occupying 25GB of space. Is it a general case, or am I doing any wrong ??
I have been exploring various memory management techniques and am exhausted with all of them. I wanted your opinions.

Many thanks.

**Comment by Nanne** [comment]
k=1024 refers to the num_clusters param? Because in that case that'd be much higher than default (which is 64)

**Comment by Anuradha-Uggi** [comment]
Thank you very much for the quick reply.
yes k=1024 refers to num_clusters.
I have appended the NetVLAD layer to the intermediate layer with spatial (64 by 64) and channel dimensions (256). Training batch size=1.
The total parameters of the resultant vector from NetVLAD = 6*1024*256 = 1.57 million, which is very small. Here 6 is the number of concatenated images per iteration, i.e. (qury+pos+4 negs).
Even for such a small number of parameters (~1.6 million), occupying 25GB of space is surprising. I don't know where I am making a mistake. Does the 25GB also include the calculations that happen in netvlad.py?

Many thanks

**Comment by Nanne** [comment]
Try setting num_clusters to a way smaller number, like the default 64. A netvlad vector of 262.144 is massive, because you'd have one for every image in the batch and it would be used in gradient computation.

**Comment by Anuradha-Uggi** [comment]
The Cuda issue occurs right after passing vgg feature batch to the NatVLAD layer. Feature maps from all layers of vgg16 cost around 48 mil, which occupies ~9GB. Then isn't it surprising to see 1.57mil features exploding the memory with size 25GB, or am I missing anything?
![encAfterBeforeDetach](https://user-images.githubusercontent.com/77561069/207313421-da0babe4-fa2a-4653-a0ac-2aca209b1033.png)
The above picture is about the memory consumption for feature maps across each layer. 

![NetVLAD_Inside_Batch](https://user-images.githubusercontent.com/77561069/207313790-91e2125a-0a7a-4393-a295-92874f176ca1.png)
This is before passing input to NetVLAD and after passing input to it.

**Comment by Nanne** [comment]
The intermediate steps of the NetVlad layer (e.g., calculating residuals) uses quite big matrices, and it takes memory to store values for gradient computation - beyond what the shape of the output is. Convolutional layers are much more efficient in that respect. 

Moreover, I also don't see why you'd want to set num_clusters that high; practically you wouldn't have much use for such big clusters when doing retrieval - if you can even fit it in memory to do kNN on..

Lowering num_clusters will solve the problem.
