### ISSUE TITLE
There is no specific data of the image in the【pitts30k_train.mat】 file?

### ISSUE THREAD

**Issue by wpumain** [Nanne/pytorch-NetVlad#81]
https://www.di.ens.fr/willow/research/netvlad/data/netvlad_v100_datasets.tar.gz。
I downloaded the netvlad_v100_datasets.tar.gz file from the download link you gave in the readme.md file.
There are many mat files in the netvlad_v100_datasets.tar.gz  file, such as pitts30k_train.mat.
The storage path of each photo and the coordinates of each image are stored in the mat file, but there is no specific information about each image, right? 
For example, the path of a image stored in the mat file is ''000/000426_pitch1_yaw1.jpg'', so where can I get the image 000426_pitch1_yaw1.jpg?

**Comment by Nanne** [comment]
That file is just the dataset specification, you still need to download the actual images; see here for more info: https://github.com/Relja/netvlad/issues/42
