### ISSUE TITLE
What is the mathematical formula on which these lines of code are based?

### ISSUE THREAD

**Issue by wpumain** [Nanne/pytorch-NetVlad#83]
I read your code carefully, it is well written and I learned a lot, thank you for sharing.
 But I don't understand why these pieces of code are calculated in this way, and I can't find the answer in the original paper of NetVlad. Can you guide me? Thanks
https://github.com/Nanne/pytorch-NetVlad/blob/8f7c37ba7a79a499dd0430ce3d3d5df40ea80581/netvlad.py#L39
https://github.com/Nanne/pytorch-NetVlad/blob/8f7c37ba7a79a499dd0430ce3d3d5df40ea80581/netvlad.py#L41
https://github.com/Nanne/pytorch-NetVlad/blob/8f7c37ba7a79a499dd0430ce3d3d5df40ea80581/netvlad.py#L43
https://github.com/Nanne/pytorch-NetVlad/blob/8f7c37ba7a79a499dd0430ce3d3d5df40ea80581/netvlad.py#L53

**Comment by Nanne** [comment]
Some more discussion on the Netvlad versions can be found here: https://github.com/Relja/netvlad/blob/master/README_more.md#netvlad-versions

I don't recall if there is much on the initialisation in the paper; I just followed their matlab implementation and translated it to python.
