### ISSUE TITLE
Where C_ks are getting updated in the code

### ISSUE THREAD

**Issue by Anuradha-Uggi** [Nanne/pytorch-NetVlad#90]
Hi @Nanne 
I have a doubt. We see a direct relation between weights (W_k, b_k) and cluster centroids C_k. **As Weights get updated during Conv backprop., the change should also be reflected in the Cks**. Except in the weight initialization function, I don't see where this relation between W_k, b_k, and Ck is used and where C_ks are updated. 

Plz clarify if you have understood it. 

Thanks
Anu

**Comment by Nanne** [comment]
I'm not quite sure if I get the question. But the NetVlad layer is part of the model, and the centroids are learnable weights. So when we initialise the optimiser the centroid weights are part of that: https://github.com/Nanne/pytorch-NetVlad/blob/master/main.py#L446-L454

Just backpropping through the model will update them.

**Comment by Anuradha-Uggi** [comment]
From #57 and #60 netvlad.py, we get direct access to conv.weight and conv.bias from convolutional layer parameters. But how centroids are being learned is a little confusing. Adding centroids to the list of nn.Parameters, still how these are learned.

**Comment by Nanne** [comment]
That is just the initialisation based on clustering. Please check out the papers for details on that.

Once they're initialised they're optimised with the rest of the network through backprop.
