### ISSUE TITLE
 Question about the number of Negatives during training process.

### ISSUE THREAD

**Issue by euncheolChoi** [Nanne/pytorch-NetVlad#92]
![negatives](https://github.com/Nanne/pytorch-NetVlad/assets/86426437/34ddde13-def6-443f-86bd-ce82c2f6fd69)

I have a question about the number of Negative samples that consists training triplets. During a traing process, i noticed that the number of negative samples did not remain constant and fluctuated significantly as shown in the figure above.

Actually, i combined the NetVLAD code with MixVPR Network (https://github.com/amaralibey/MixVPR) to construct the triplet needed to train the MixVPR Network.

I would like to ask if you have experienced a decrease in the number of negative samples as in the above case. Thanks in advance.

**Comment by Nanne** [comment]
The aim of the negative selection is to find *hard* negatives, where hard is determined based on distance: https://github.com/Nanne/pytorch-NetVlad/blob/master/pittsburgh.py#L239. As training progresses there will be fever negatives that meet this criteria, and thus the number of negative samples selected will drop. 

To me this seems like a good thing, if the nNeg doesn't drop then your model isn't training well.

**Comment by euncheolChoi** [comment]
Thank you for your quick response. It was very helpful for my understanding.  : )
