### ISSUE TITLE
No found image in pitts250k

### ISSUE THREAD

**Issue by Junshuai1024** [Nanne/pytorch-NetVlad#93]
Pitts250k dataset have on image.
FileNotFoundError: [Errno 2] No such file or directory: '.../pittsburgh250k/raw_data/000/000426_pitch1_yaw1.jpg'

**Comment by Nanne** [comment]
The dataset is not included in this repo, please obtain it independently. See https://github.com/Relja/netvlad/issues/42

**Comment by liuqinglong110** [comment]
I found the download link     [https://data.ciirc.cvut.cz/public/projects/2015netVLAD/Pittsburgh250k/](url)
I was discovered by a issue related links: [https://github.com/Nanne/pytorch-NetVlad/issues/19 ](url)
suggested that read.
